### ISSUE TITLE
loading silently fails on unkown file endings

### ISSUE THREAD

**Issue by benreh** [ORB-HD/MeshUp#2]
The function MeshupApp::parseArguments(...) tries to determine the type of file (lua, animation, forces) by looking at the ending. 
While this is by itself a very questionable practise, it also fails silently if the file type cannot be determined by this function. 
Please add an "else" case to at least give a warning on the console.

**Comment by Felix5721** [comment]
Added a warning that the file will be ignored. <07814a04534671ec610a81cc542c315f84157279>
