### ISSUE TITLE
failed Assertion if  number of columns mismatch

### ISSUE THREAD

**Issue by benreh** [ORB-HD/MeshUp#3]
If loading an Animation file without Meshup-header (plain csv) the number of columns need to directly match the number of DOF +1 for time in the luamodel, or else a very cryptic assertion is triggered in
Animation::getKeyFrameAtFrameIndex (..), as one index is out of bound. 

Suggestion: Be more flexible and use only data that is in the CSV or at least throw an understandable error message.

**Comment by Felix5721** [comment]
Added checks to prevent using animation files that do not conaint enough information to be displayed correctly. https://github.com/ORB-HD/MeshUp/commit/47ef54edb8746e134302ad4ac211a03d7fb3f319
